### ISSUE TITLE
Reports coverage of 90.9% as 9%

### ISSUE THREAD

**Issue by LukasHechenberger** [ls-age/esdoc-plugin-require-coverage#2]
Error stack:

```
{path}/node_modules/esdoc-plugin-require-coverage/out/Plugin.js:367
        throw new Error('Coverage is at ' + covered + '%, (' + this._required + '% required)' + _os.EOL);
        ^

Error: Coverage is at 9%, (90% required)

    at Plugin.checkCoverage ({path}/node_modules/esdoc-plugin-require-coverage/out/Plugin.js:367:15)
    at Object.onComplete ({path}/node_modules/esdoc-plugin-require-coverage/out/require-coverage.js:200:10)
    at Plugin._execHandler ({path}/node_modules/esdoc/out/src/Plugin/Plugin.js:57:26)
    at Plugin.onComplete ({path}/node_modules/esdoc/out/src/Plugin/Plugin.js:151:10)
    at Function.generate ({path}/node_modules/esdoc/out/src/ESDoc.js:143:22)
    at ESDocCLI.exec ({path}/node_modules/esdoc/out/src/ESDocCLI.js:75:23)
    at Object.<anonymous> ({path}/node_modules/esdoc/out/src/ESDocCLI.js:186:7)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)

```

**Comment by LukasHechenberger** [comment]
Actually ran into #1
